### PR TITLE
8 - persist the keyboard statuses on each row play

### LINKED ISSUE #14: 8 - persist the keyboard statuses on each row play
When in daily mode persist the keyboard letter statuses to local storage on each play of the row.  

How to test
1. Play a couple of rows of the game
2. Refresh the browser
=> the keyboard should show the status colours that were present before the browser refresh

### PR DESCRIPTION
**Pull request by ThatGuyHughesy**
Fixes #14

### CODE REVIEW

**Comment by LindaKeating** [comment]
This is fantastic! Míle Buíochas.

There is just one small bug left to correct with this. 

Player plays row of game
Player switches to Mód Cleachtaigh
Player plays row of game in Practice Mode
Player switches back to Daily Mode (Mód Laethúil)

Player now sees letter statuses associated with the practice game instead of daily game

https://deploy-preview-23--foclach.netlify.app/

I can merge the changes and file a bug for that edge case.
Or if you think you know an easy solution and want to include it with this PR ...

Up to you? I'm happy either way.  This PR is a definite improvement on current status and I'm delighted that you've chosen to contribute.

**Comment by ThatGuyHughesy** [comment]
Apologies, I didn't think to test Mód Cleachtaigh I will know for the next time, thanks for pointing it out!

I've update the pull request which should hopefully fix this issue.

**Comment by LindaKeating** [comment]
I didn't think of it myself when I wrote the issue up. I only thought to check it once I saw your PR.

Over the moon to have a new contributor.  GRMMMMA!

**Comment by LindaKeating** [comment]
I've merged but I'll bump the version number on package.json on main branch so cachebusting kicks in. I should really update the README or CONTRIBUTING file to include that detail..

**Pull request merged**
